version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017

  api2: 
    image: visualizacionesdatalat/backend-registros-usuario
    ports:
      - 3005:3005
    command: npm run start
    environment:
      DB_URL: mongodb://mongodb:27017/Datalat
      PORT_U: 3005
    env_file:
      - .env
    depends_on:
      - mongodb

  api: 
    image: visualizacionesdatalat/registros-backend
    ports:
      - 3001:3001
    command: npm run start
    environment:
      DB_URL_U: mongodb://mongodb:27017/Datalat
      PORT: 3001
    env_file:
      - .env
    depends_on:
      - mongodb